// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0NakXae44C7JFV8zyAw8f5f122TMQdFg',
    appId: '1:701558166721:web:6eb356c01c2c5819eb7040',
    messagingSenderId: '701558166721',
    projectId: 'chatapp-846fc',
    authDomain: 'chatapp-846fc.firebaseapp.com',
    databaseURL: 'https://chatapp-846fc-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-846fc.appspot.com',
    measurementId: 'G-PP0VV6EZ3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn49kDQPkU3pW6oT2tnWJq6astFIY3adI',
    appId: '1:701558166721:android:aebc057c79ec4afaeb7040',
    messagingSenderId: '701558166721',
    projectId: 'chatapp-846fc',
    databaseURL: 'https://chatapp-846fc-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-846fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSQzwtPRWYPIRLf-I1WgVXhE80JrCGeBo',
    appId: '1:701558166721:ios:7aff64588ac341c5eb7040',
    messagingSenderId: '701558166721',
    projectId: 'chatapp-846fc',
    databaseURL: 'https://chatapp-846fc-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-846fc.appspot.com',
    iosBundleId: 'com.example.summarizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSQzwtPRWYPIRLf-I1WgVXhE80JrCGeBo',
    appId: '1:701558166721:ios:fa3f5eb31bad8a24eb7040',
    messagingSenderId: '701558166721',
    projectId: 'chatapp-846fc',
    databaseURL: 'https://chatapp-846fc-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-846fc.appspot.com',
    iosBundleId: 'com.example.summarizer.RunnerTests',
  );
}
